### ISSUE TITLE
How to use this gem

### ISSUE THREAD

**Issue by theodorosploumis** [fhidalgo/attacks_checker#1]
Hi, I would like to use this tool to inspect some malicious logs. But I couldn't find out how to do this. There is a config.rb file but how can I include it on runtime?

Thanks.

**Comment by fhidalg0** [comment]
Hi,
This gem was build as part of a work interview.
It is not design to be integrated into rails.
At runtime it listen to linux kernel events created when INPUT_LOG is modified.

To run it you just need to execute bin/checker.

**Comment by theodorosploumis** [comment]
I just wan to parse some static apache log files, not using rails.

**Comment by fhidalg0** [comment]
It is not prepared to parse several files, it is prepared to parse just one file and do it while the file is changing.

In the config file you can find the INPUT_LOG constant setted up as 'access.log', by default it will parse an access.log being modified in realtime. It won't parse a static file.
